### ISSUE TITLE
There are still much left for improvement

### ISSUE THREAD

**Issue by hyahm** [jhuix/vue-showdowns-editor#1]
- no document
- how to use in vue
- not support local upload image 
- code highlight not pretty

nice:
-  support  mermaid
-  support asciimath
-  support Plantuml

expecting...
may be you can use for reference ： https://github.com/hinesboy/mavonEditor

**Comment by jhuix** [comment]
First of all, thank you for your suggestions.
In the future, we will gradually improve the functions and documents.
As for how to use it in Vue, you can refer to [the example code](https://github.com/jhuix/showdown-markdown-editor/tree/master/examples) temporarily
