### ISSUE TITLE
save / open file?

### ISSUE THREAD

**Issue by xu4wang** [jhuix/vue-showdowns-editor#2]
Hi jhuix,

thanks for the project. nice work!

Is there any plan to support open/save file?

BR,
Austin

**Comment by jhuix** [comment]
There will be plans to support open/save files in the near future.

**Comment by jhuix** [comment]
For personal use in writing, you can also consider downloading the vscode extension named [MarkDown Preview Showdown (MDPS)](https://marketplace.visualstudio.com/items?itemName=jhuix.markdown-preview-showdown) developed by me.

**Comment by xu4wang** [comment]
> There will be plans to support open/save files in the near future.

thanks looking forward
