### ISSUE TITLE
default dummy text

### ISSUE THREAD

**Issue by maltegrosse** [jhuix/vue-showdowns-editor#4]
Hello,

when setting the locals to en-gb, and then clicking "insert url, ordered list etc.." a text is inserted in non english.
can this be changed?

**Comment by jhuix** [comment]
Try the new version 1.0.4 again. 
Default dummy text is english when set the locals to except for zh-cn and zh-cht.

**Comment by jhuix** [comment]
> Hello,
> 
> when setting the locals to en-gb, and then clicking "insert url, ordered list etc.." a text is inserted in non english.
> can this be changed?

Try the new version >=1.0.4 again.
